apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      serviceAccountName: bot-sa
      containers:
      - name: bot
        image: suhailakthar/k8s_chatbot:v4
        env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-secret
              key: BOT_TOKEN
