apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama-pvc

      containers:
      - name: ollama
        image: ollama/ollama
        ports:
        - containerPort: 11434

        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama

        lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - |
                  sleep 10
                  ollama pull llama2

        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: ollama
spec:
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434
